PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS item (
  id   INTEGER PRIMARY KEY AUTOINCREMENT,
  ts   INTEGER NOT NULL,
  task TEXT    NOT NULL
);
CREATE TABLE IF NOT EXISTS pick (
  id      INTEGER PRIMARY KEY AUTOINCREMENT,
  item_id INTEGER NOT NULL REFERENCES item(id) ON DELETE CASCADE,
  rank    INTEGER NOT NULL,
  text    TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_pick_item ON pick(item_id);
