name: ANNI Approve CI
on:
  push:
    branches: [ "main" ]
    paths:
      - 'approve_srv.py'
      - 'Dockerfile.approve'
      - '.github/workflows/anni-approve.yml'
  workflow_dispatch:
jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Build
        run: docker build -f Dockerfile.approve -t ghcr.io/${{ github.repository }}/anni-approve:sha-${{ github.sha }} .
      - name: Push
        run: docker push ghcr.io/${{ github.repository }}/anni-approve:sha-${{ github.sha }}
