name: Smoke Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        
    - name: Run smoke tests
      run: |
        echo "Running smoke tests..."
        python scripts/smoke_stack.py
        python scripts/smoke_tc_claim_guard.py
        python scripts/smoke_trancespell.py
        
    - name: Upload test logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: smoke-test-logs
        path: |
          *.log
          /tmp/*.log
        retention-days: 7
